config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  root 'welcome#index'
  resources :microposts, only:[:create, :destroy]
  resources :home do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only:[:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><% msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <h3>今の気持ちを投稿して</h3>
    <%= f.text_area :content, placeholder: "Write your feeling", class: "form-control" %>
  </div>
    <%= f.submit "投稿", class: "btn btn-primary mb-2" %></br>
    <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png" %>
<% end %>

<script>
$('#micropost_picture').bind('change', function(){
  var size_in_megabytes = this.files[0].size/1024/1024;
  if(size_in_megabytes > 5){
    alert('最大サイズは5MBです。小さいファイルに変更してください');
  }
});
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_home_path(@user) %>">
    <strong id="following" class="stats">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_home_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>