config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  root 'welcome#index'
  resources :microposts, only:[:create, :destroy]
  resources :home do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only:[:create, :destroy]
end

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <%if user_signed_in? %>
      <h3><b><%= link_to 'Insta App', home_path(current_user), class: 'text-white' %></b></h3>
    <% else %>
      <h3><b><%= link_to 'Insta App', root_path, class: 'text-white' %></b></h3>
    <% end %>
    <% if user_signed_in? %>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#header-menu" >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="header-menu">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><strong><%= link_to current_user.name, home_path(current_user), class: 'text-white' %></strong></li>
          <li class="nav-item"><%= link_to 'All Users', home_index_path, class: 'text-white' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="dropdown-toggle text-white" data-toggle="dropdown">設定</a>
            <ul class="dropdown-menu">
              <li class="dropdown-item"><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      </div>
    <% else %>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#header-menu" >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="header-menu">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><%= link_to '会員登録', new_user_registration_path, class: 'text-white' %></li>
          <li class="nav-item"><%= link_to 'ログイン', new_user_session_path, class: 'text-white ' %></li>
        </ul>
      </div>
    <% end %>
  </nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= bootstrap_class_for(key) %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_user_info.html.erb
<% if user_signed_in? %>
  <%= current_user.name %>
  [<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>]
<% else %>
  <%= link_to 'Sign in with Facebook', user_facebook_omniauth_authorize_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta  name="viewport" content="width=device-width">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>